CoverOptions 에서 사용하는 default key 를 const 로 셋팅하여 외부에서 참조 가능하도록 함
ridi/cover pull request #4
Opened 2019-04-16 11:38 UTC by iiogmgo

- CoverOptions 에서 default 로 셋팅되는 key 값을 const 로 셋팅하였습니다
  - 표지서비스 개선을 위해 default key를 외부(표지서비스)에서 참조하기 위함입니다 
  - 표지서비스에서 해당 default key 를 통해 람다 서빙용 이미지 파일명을 제너레이트할 예정입니다

2019-04-17 08:07 UTC, ssaifriend requested changes
1. Travis CI 결과 확인 부탁드릴께요.
2. 일관성있게 모든 상수를 const 화하는게 어떨까요?

2019-04-19 05:51 UTC, iiogmgo commented
@ssaifriend ci 모두 통과한 것으로 나오는데 어떤 것 말씀하시는 건가요?

2019-04-19 05:53 UTC, iiogmgo commented
@ssaifriend default key 외에는 사용처가 $OPTIONS 한 곳이라 const 화의 의미가 있는지 모르겠습니다. 추후 사용처가 2곳 이상이 되면 const화를 진행하면 좋을 것 같아요.

2019-04-19 06:39 UTC, ssaifriend approved these changes

2019-04-19 06:43 UTC, merged